# Generated by Django 4.1 on 2023-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='category',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('IE', 'Import/Export'), ('DO', 'Division Office'), ('FO', 'Food Office'), ('FFSQRD', 'FFSQRD'), ('FTDND', 'FTDND'), ('NFFRL', 'NFFRL'), ('A', 'Account')], max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='form_type',
            field=models.CharField(blank=True, choices=[('Account', 'Account'), ('Report', 'Report')], max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('V', 'Verifier'), ('DE', 'Data Entry')], default='ee', max_length=255),
            preserve_default=False,
        ),
    ]
