# Generated by Django 4.1 on 2023-06-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_office',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='office',
            name='category',
            field=models.CharField(choices=[('IE', 'Import/Export'), ('DO', 'Division Office'), ('FO', 'Food Office'), ('dd', 'dd')], max_length=255),
        ),
    ]
