# Generated by Django 4.1 on 2023-06-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_user_office_alter_office_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_office',
        ),
    ]
