# Generated by Django 4.1 on 2023-06-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_category_office_delete_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_category',
            field=models.CharField(blank=True, choices=[('IE', 'Import/Export'), ('DO', 'Division Office'), ('FO', 'Food Office'), ('FFSQRD', 'FFSQRD'), ('FTDND', 'FTDND'), ('NFFRL', 'NFFRL'), ('A', 'Account')], max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='ww', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
