<<<<<<< HEAD
# Generated by Django 4.1 on 2023-06-28 11:52
=======
# Generated by Django 4.1 on 2023-06-29 05:22
>>>>>>> c5f56610d9290d0f5115896ed9b3e5c0ecd688dc

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('account', '0004_remove_customuser_user_office'),
=======
    dependencies = [
        ("account", "0004_remove_customuser_user_office"),
>>>>>>> c5f56610d9290d0f5115896ed9b3e5c0ecd688dc
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='office',
            name='category',
            field=models.CharField(choices=[('IE', 'Import/Export'), ('DO', 'Division Office'), ('FO', 'Food Office')], max_length=255),
=======
            model_name="office",
            name="category",
            field=models.CharField(
                choices=[
                    ("IE", "Import/Export"),
                    ("DO", "Division Office"),
                    ("FO", "Food Office"),
                ],
                max_length=255,
            ),
>>>>>>> c5f56610d9290d0f5115896ed9b3e5c0ecd688dc
        ),
    ]
