# Generated by Django 4.1 on 2023-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_department_category_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('V', 'Verifier'), ('DE', 'Data Entry')], max_length=255),
        ),
    ]
