# Generated by Django 4.1 on 2023-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('V', 'Verifier'), ('DE', 'Data Entry')], max_length=255),
        ),
    ]
