# Generated by Django 4.1 on 2023-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_office_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
