# Generated by Django 4.1 on 2023-07-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_office_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="office",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
