# Generated by Django 4.1 on 2023-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='department_category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='office',
            name='category',
            field=models.CharField(choices=[('IE', 'Import/Export'), ('DO', 'Division Office'), ('FO', 'Food Office')], default='ss', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
