deployment:
  tasks:
    - export DEPLOYPATH=/home/kantggjb/pme1/ #this is original
    - /bin/cp -r account $DEPLOYPATH
    #- /bin/cp -r fpn $DEPLOYPATH             #main project dir
    - /bin/cp -r main $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
    - /bin/cp -r templates $DEPLOYPATH
    - /bin/cp -r detail $DEPLOYPATH
  
  
