# Generated by Django 4.1 on 2023-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BittiyaBibaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_pujigat', models.FloatField(blank=True)),
                ('yearly_chalu', models.FloatField(blank=True)),
                ('monthly_pujigat', models.FloatField(blank=True)),
                ('monthly_chalu', models.FloatField(blank=True)),
                ('monthly_rajaswo', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NamunaBibaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.CharField(blank=True, max_length=255)),
                ('oil', models.CharField(blank=True, max_length=255)),
                ('fruits', models.CharField(blank=True, max_length=255)),
                ('spice', models.CharField(blank=True, max_length=255)),
                ('tea', models.CharField(blank=True, max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255)),
                ('khadanna', models.CharField(blank=True, max_length=255)),
                ('water', models.CharField(blank=True, max_length=255)),
                ('sweets', models.CharField(blank=True, max_length=255)),
                ('confectionery', models.CharField(blank=True, max_length=255)),
                ('meat', models.CharField(blank=True, max_length=255)),
                ('grain', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatraJari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.CharField(blank=True, max_length=255)),
                ('oil', models.CharField(blank=True, max_length=255)),
                ('fruits', models.CharField(blank=True, max_length=255)),
                ('spice', models.CharField(blank=True, max_length=255)),
                ('tea', models.CharField(blank=True, max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255)),
                ('khadanna', models.CharField(blank=True, max_length=255)),
                ('water', models.CharField(blank=True, max_length=255)),
                ('sweets', models.CharField(blank=True, max_length=255)),
                ('confectionery', models.CharField(blank=True, max_length=255)),
                ('meat', models.CharField(blank=True, max_length=255)),
                ('grain', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatraNabikaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.CharField(blank=True, max_length=255)),
                ('oil', models.CharField(blank=True, max_length=255)),
                ('fruits', models.CharField(blank=True, max_length=255)),
                ('spice', models.CharField(blank=True, max_length=255)),
                ('tea', models.CharField(blank=True, max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255)),
                ('khadanna', models.CharField(blank=True, max_length=255)),
                ('water', models.CharField(blank=True, max_length=255)),
                ('sweets', models.CharField(blank=True, max_length=255)),
                ('confectionery', models.CharField(blank=True, max_length=255)),
                ('meat', models.CharField(blank=True, max_length=255)),
                ('grain', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UdyogSifaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.CharField(blank=True, max_length=255)),
                ('oil', models.CharField(blank=True, max_length=255)),
                ('fruits', models.CharField(blank=True, max_length=255)),
                ('spice', models.CharField(blank=True, max_length=255)),
                ('tea', models.CharField(blank=True, max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255)),
                ('khadanna', models.CharField(blank=True, max_length=255)),
                ('water', models.CharField(blank=True, max_length=255)),
                ('sweets', models.CharField(blank=True, max_length=255)),
                ('confectionery', models.CharField(blank=True, max_length=255)),
                ('meat', models.CharField(blank=True, max_length=255)),
                ('grain', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UjuriGunaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gunaso_petika', models.PositiveIntegerField(blank=True)),
                ('gunaso_adhikari', models.PositiveIntegerField(blank=True)),
                ('zilla', models.PositiveIntegerField(blank=True)),
                ('banijya', models.PositiveIntegerField(blank=True)),
                ('patra', models.PositiveIntegerField(blank=True)),
                ('akhtiyar', models.PositiveIntegerField(blank=True)),
                ('patrakar', models.PositiveIntegerField(blank=True)),
                ('sarkar', models.PositiveIntegerField(blank=True)),
                ('upavokta', models.PositiveIntegerField(blank=True)),
                ('others', models.PositiveIntegerField(blank=True)),
                ('jamma', models.PositiveIntegerField(blank=True)),
                ('sambodhan', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
