# Generated by Django 4.1 on 2023-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logobitaran',
            name='type',
            field=models.CharField(choices=[('green', 'हरियो स्टिकर'), ('yellow1', 'पेहेलोमा एउटा रातो धर्सो'), ('yellow2', 'पेहेलोमा दुइटा रातो धर्सो'), ('red', 'रातो स्टिकर')], max_length=50),
        ),
    ]
