# Generated by Django 4.1 on 2023-06-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bittiyabibaran',
            name='name',
        ),
    ]
