# Generated by Django 4.1 on 2023-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_chalu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_pujigat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_rajaswo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='yearly_chalu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='yearly_pujigat',
            field=models.FloatField(null=True),
        ),
    ]
