# Generated by Django 4.1 on 2023-06-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bittiyabibaran_monthly_chalu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_chalu',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_pujigat',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_rajaswo',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='yearly_chalu',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='yearly_pujigat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
