# Generated by Django 4.1 on 2023-06-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bittiyabibaran_monthly_chalu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_chalu',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_pujigat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='monthly_rajaswo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='yearly_chalu',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bittiyabibaran',
            name='yearly_pujigat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='akhtiyar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='banijya',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='gunaso_adhikari',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='gunaso_petika',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='jamma',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='others',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='patra',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='patrakar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='sambodhan',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='sarkar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='upavokta',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ujurigunaso',
            name='zilla',
            field=models.PositiveIntegerField(),
        ),
    ]
