# Generated by Django 4.1 on 2023-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aayatniryat_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aayatniryat',
            name='type',
            field=models.CharField(choices=[('milk', 'दुध तथा दुध पदार्थ'), ('oil', 'तेल तथा घिउ जन्य'), ('fruits', 'फल तथा सागपात'), ('spice', 'मसला'), ('tea', 'चिया, कफि'), ('salt', 'नुन'), ('khadanna', 'खाद्यान्न दलहन र सोवाट बनेका'), ('water', 'प्र. पिउने पानी'), ('sweets', 'गुलियो पदार्थ'), ('confectionery', 'कन्फेक्सनरी'), ('meat', 'मासु तथा मासुजन्य'), ('grain', 'दाना'), ('others', 'अन्य')], max_length=100),
        ),
        migrations.AlterField(
            model_name='anugamanbibaran',
            name='type',
            field=models.CharField(choices=[('udyog', 'उद्योग'), ('pasal', 'पसल'), ('supermarket', 'सुपरमार्केट'), ('godam', 'गोदाम'), ('hotel', 'होटल, रेस्टुरेन्ट, मिठाई पसल आदी'), ('dana', 'दाना पदार्थ'), ('anya', 'अन्य')], max_length=100),
        ),
        migrations.AlterField(
            model_name='namunabisleysan',
            name='type',
            field=models.CharField(choices=[('milk', 'दुध तथा दुध पदार्थ'), ('oil', 'तेल तथा घिउ जन्य'), ('fruits', 'फल तथा सागपात'), ('spice', 'मसला'), ('tea', 'चिया, कफि'), ('salt', 'नुन'), ('khadanna', 'खाद्यान्न दलहन र सोवाट बनेका'), ('water', 'प्र. पिउने पानी'), ('sweets', 'गुलियो पदार्थ'), ('confectionery', 'कन्फेक्सनरी'), ('meat', 'मासु तथा मासुजन्य'), ('grain', 'दाना'), ('others', 'अन्य')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prayogsalabisleysan',
            name='type',
            field=models.CharField(choices=[('milk', 'दुध तथा दुध पदार्थ'), ('oil', 'तेल तथा घिउ जन्य'), ('fruits', 'फल तथा सागपात'), ('spice', 'मसला'), ('tea', 'चिया, कफि'), ('salt', 'नुन'), ('khadanna', 'खाद्यान्न दलहन र सोवाट बनेका'), ('water', 'प्र. पिउने पानी'), ('sweets', 'गुलियो पदार्थ'), ('confectionery', 'कन्फेक्सनरी'), ('meat', 'मासु तथा मासुजन्य'), ('grain', 'दाना'), ('others', 'अन्य')], max_length=100),
        ),
    ]
