# Generated by Django 4.1 on 2023-06-30 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_aayatniryat_type_alter_anugamanbibaran_type_and_more"),
        ("main", "0006_alter_aayatniryat_created_by_and_more"),
    ]

    operations = []
