# Generated by Django 4.1 on 2023-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_patrajari_confectionery_alter_patrajari_fruits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnugamanBibaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('udyog', 'udyog'), ('pasal', 'pasal'), ('supermarket', 'supermarket'), ('godam', 'godam'), ('hotel', 'hotel'), ('dana', 'dana'), ('anya', 'anya')], max_length=100)),
                ('patak', models.PositiveIntegerField(blank=True, default=0)),
                ('sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('pragati', models.PositiveIntegerField(blank=True, default=0)),
                ('kaifiyat', models.TextField(blank=True, default='')),
            ],
        ),
    ]
