# Generated by Django 4.1 on 2023-06-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_anugamanbibaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamunaBisleysan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('milk', 'milk'), ('oil', 'oil'), ('fruits', 'fruits'), ('spice', 'spice'), ('tea', 'tea'), ('salt', 'salt'), ('khadanna', 'khadanna'), ('water', 'water'), ('sweets', 'sweets'), ('confectionery', 'confectionery'), ('meat', 'meat'), ('others', 'others'), ('grain', 'grain')], max_length=100)),
                ('ekai', models.CharField(blank=True, choices=[('S', 'संख्या'), ('P', 'पटक')], max_length=10)),
                ('lakshya', models.PositiveIntegerField(blank=True, default=0)),
                ('pragati1', models.PositiveIntegerField(blank=True, default=0)),
                ('mahina_pragati', models.PositiveIntegerField(blank=True, default=0)),
                ('sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('parameter', models.PositiveIntegerField(blank=True, default=0)),
                ('pragati2', models.PositiveIntegerField(blank=True, default=0)),
                ('pratisat', models.FloatField(blank=True, default=0)),
                ('kaifiyat', models.TextField(blank=True, default='')),
            ],
        ),
    ]
