# Generated by Django 4.1 on 2023-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_namunabisleysan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AayatNiryat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('milk', 'milk'), ('oil', 'oil'), ('fruits', 'fruits'), ('spice', 'spice'), ('tea', 'tea'), ('salt', 'salt'), ('khadanna', 'khadanna'), ('water', 'water'), ('sweets', 'sweets'), ('confectionery', 'confectionery'), ('meat', 'meat'), ('others', 'others'), ('grain', 'grain')], max_length=100)),
                ('ekai', models.CharField(blank=True, choices=[('S', 'संख्या'), ('P', 'पटक')], max_length=10)),
                ('b_lakshya', models.PositiveIntegerField(blank=True, default=0)),
                ('c_lakshya', models.PositiveIntegerField(blank=True, default=0)),
                ('c_pragati', models.PositiveIntegerField(blank=True, default=0)),
                ('m_pragati', models.PositiveIntegerField(blank=True, default=0)),
                ('pratikul_n', models.PositiveIntegerField(blank=True, default=0)),
                ('pratikul_p', models.PositiveIntegerField(blank=True, default=0)),
                ('h_pragati', models.PositiveIntegerField(blank=True, default=0)),
                ('h_pratisat', models.PositiveIntegerField(blank=True, default=0)),
                ('kaifiyat', models.TextField(blank=True, default='')),
            ],
        ),
    ]
