# Generated by Django 4.1 on 2023-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_aayatniryat_is_rejected_anugamanbibaran_is_rejected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aayatniryat",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anugamanbibaran",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bittiyabibaran",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailanugaman",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailgunaso",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailhotel",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailmudha",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailrbpa",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailregistration",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailrenew",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detailudyog",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="khadyaprasodhan",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logobitaran",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="namunabibaran",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="namunabisleysan",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patrajari",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patranabikaran",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pragatibibaran",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prayogsalabisleysan",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="udyogsifaris",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ujurigunaso",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
