# Generated by Django 4.1 on 2023-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aayatniryat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayogsalaBisleysan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('milk', 'milk'), ('oil', 'oil'), ('fruits', 'fruits'), ('spice', 'spice'), ('tea', 'tea'), ('salt', 'salt'), ('khadanna', 'khadanna'), ('water', 'water'), ('sweets', 'sweets'), ('confectionery', 'confectionery'), ('meat', 'meat'), ('grain', 'grain'), ('others', 'others')], max_length=100)),
                ('b_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('b_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('u_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('u_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('ay_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('ay_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('v_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('v_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('k_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('k_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('a_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('a_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('kul_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('kul_pratikul', models.PositiveIntegerField(blank=True, default=0)),
                ('sample', models.PositiveIntegerField(blank=True, default=0)),
                ('kaifiyat', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='aayatniryat',
            name='type',
            field=models.CharField(choices=[('milk', 'milk'), ('oil', 'oil'), ('fruits', 'fruits'), ('spice', 'spice'), ('tea', 'tea'), ('salt', 'salt'), ('khadanna', 'khadanna'), ('water', 'water'), ('sweets', 'sweets'), ('confectionery', 'confectionery'), ('meat', 'meat'), ('grain', 'grain'), ('others', 'others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='namunabisleysan',
            name='type',
            field=models.CharField(choices=[('milk', 'milk'), ('oil', 'oil'), ('fruits', 'fruits'), ('spice', 'spice'), ('tea', 'tea'), ('salt', 'salt'), ('khadanna', 'khadanna'), ('water', 'water'), ('sweets', 'sweets'), ('confectionery', 'confectionery'), ('meat', 'meat'), ('grain', 'grain'), ('others', 'others')], max_length=100),
        ),
    ]
