# Generated by Django 4.1 on 2023-07-10 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0012_barisklakshya"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BariskLakshya",
            new_name="BarsikLakshya",
        ),
    ]
