# Generated by Django 4.1 on 2023-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_logobitaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhadyaPrasodhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miti', models.DateField(blank=True, null=True)),
                ('abadhi', models.CharField(blank=True, default='', max_length=255)),
                ('naam', models.CharField(blank=True, default='', max_length=255)),
                ('sthan', models.CharField(blank=True, default='', max_length=255)),
                ('m_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('p_sankhya', models.PositiveIntegerField(blank=True, default=0)),
                ('sanyojak', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('prasikshak', models.CharField(blank=True, default='', max_length=255)),
                ('nikaya', models.TextField(blank=True, default='')),
                ('bisaya', models.TextField(blank=True, default='')),
                ('kaifiyat', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MasikPragati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upasirshak', models.PositiveIntegerField(blank=True, default=0)),
                ('karyakram', models.CharField(blank=True, default='', max_length=255)),
                ('ekai', models.CharField(blank=True, choices=[('S', 'संख्या'), ('P', 'पटक')], max_length=15)),
                ('b_lakshya', models.PositiveIntegerField(blank=True, default=0)),
                ('m_parina', models.PositiveIntegerField(blank=True, default=0)),
                ('t_lakshya', models.PositiveIntegerField(blank=True, default=0)),
                ('t_pragati', models.PositiveIntegerField(blank=True, default=0)),
                ('t_pratisat', models.PositiveIntegerField(blank=True, default=0)),
                ('h_parinam', models.PositiveIntegerField(blank=True, default=0)),
                ('h_pratisat', models.PositiveIntegerField(blank=True, default=0)),
                ('kaifiyat', models.TextField(blank=True, default='')),
            ],
        ),
    ]
