# Generated by Django 4.1 on 2023-06-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_khadyaprasodhan_masikpragati'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAnugaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nirichad', models.CharField(blank=True, choices=[('B', 'बजार/पसल'), ('K', 'खाद्य उद्योग'), ('H', 'होटल, रेष्टुरेण्ट, मिठाई पसल'), ('S', 'संयुक्त अनुगमन'), ('D', 'दाना उद्योग'), ('A', 'अन्य')], max_length=100)),
                ('miti', models.DateField(blank=True)),
                ('naam', models.CharField(blank=True, default='', max_length=255)),
                ('thegana', models.CharField(blank=True, default='', max_length=255)),
                ('nikaya', models.CharField(blank=True, default='', max_length=255)),
                ('a_bibaran', models.CharField(blank=True, default='', max_length=255)),
                ('silbandi', models.CharField(blank=True, default='', max_length=255)),
                ('parinam', models.CharField(blank=True, default='', max_length=255)),
                ('mulya', models.CharField(blank=True, default='', max_length=255)),
                ('nirdesan', models.CharField(blank=True, default='', max_length=255)),
                ('d_bibaran', models.CharField(blank=True, default='', max_length=255)),
                ('kaifiyat', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
