# Generated by Django 4.1 on 2023-07-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_khadyaprasodhan_miti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailgunaso",
            name="p_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailgunaso",
            name="s_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailhotel",
            name="j_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailhotel",
            name="n_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailmudha",
            name="b_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailmudha",
            name="m_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailmudha",
            name="n_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailmudha",
            name="p_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailregistration",
            name="j_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailregistration",
            name="n_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailrenew",
            name="j_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailrenew",
            name="n_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailudyog",
            name="j_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="detailudyog",
            name="n_miti",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
