# Generated by Django 4.1 on 2023-07-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_detailanugaman_miti_alter_detailgunaso_p_miti_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barsiklakshya",
            name="lock",
            field=models.BooleanField(default=False),
        ),
    ]
