# Generated by Django 4.1 on 2023-07-31 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_alter_barsiklakshya_lock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barsiklakshya",
            name="lock",
        ),
    ]
